version: "3.8"
services:
    backrest:
        image: garethgeorge/backrest:latest
        container_name: backrest
        hostname: backrest
        volumes:
            - ./data/backrest:/data
            - ./config/backrest:/config
            # - /path/to/backup/data:/userdata  # Mount local paths to backup
            - ./data/restic:/repos # Mount local repos (optional for remote storage)
        environment:
            # - BACKREST_DATA=/data
            # - BACKREST_CONFIG=/config/config.json
            # - XDG_CACHE_HOME=/cache
            # - TMPDIR=/tmp
            # - TZ=America/Los_Angeles
        ports:
            - "9898:9898"
        restart: unless-stopped
