secrets:
  fullchain:
    file: ./secrets/b5nine.com-fullchain.pem
  privkey:
    file: ./secrets/b5nine.com-privkey.pem
  cfini:
    file: ./secrets/b5nine.ini

networks:
  caddy:
    external: true

services:
  caddy:
    # image: iarekylew00t/caddy-cloudflare:latest
    image: caddy/caddy:2.9-alpine
    container_name: caddy
    # restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE # If binding to ports <1024
    ports:
      - 0.0.0.0:80:80/tcp # I'm probably 100.120.70.64
      - 0.0.0.0:443:443
    volumes:
      - ./config/caddy:/etc/caddy:z
      - ./data/caddy:/var/log:z
    secrets:
      - privkey
      - fullchain
      - cfini
    networks: 
      - caddy
    configs:
      - source: Caddyfile
        target: /etc/caddy/CaddyfileMaybe
configs:
  Caddyfile:
    content: |
      strawberry fields forever