services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    # expose: [5230/tcp]
    ports:
      - 0.0.0.0:5230:5230
    volumes:
      - ./data/memos:/var/opt/memos