# networks:
#   net:
#     driver: bridge


secrets:
  fullchain:
    file: ./secrets/b5nine.com-fullchain.pem
  privkey:
    file: ./secrets/b5nine.com-privkey.pem

services:
 
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    # restart: unless-stopped
    # expose:
    #   - 9097
    ports:
      - "9097:9097"
    # networks:
    #   - net
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/authelia:/config:z
    secrets:
      - privkey
      - fullchain

  redis:
    image: redis:alpine
    container_name: redis
    # restart: unless-stopped
    volumes:
      - ./data/redis:/data:z
    expose:
      - 6379
    # networks:
    #   - net
    environment:
      - TZ=Europe/Amsterdam